### PR TITLE
Make commands OS agnostic

### LINKED ISSUE #11: Extension is only working for Linux based OS
Some of the commands are executing terminal commands, which currently only work for Linux based OS.

### PR DESCRIPTION
**Pull request by LukasBoll**
Certain commands were only working on Linux based operation systems.
This commit makes all commands OS agnostic.

Closes #11

### CODE REVIEW

**Review by eneufeld — APPROVED** [review]

**Comment by eneufeld** [comment]
thank you for the fix, it looks good to me!

**Comment by eneufeld** [comment]
It would be great if you could update the commit message to better follow the suggestion from here: 
https://chris.beams.io/posts/git-commit/
Basically adapt the message subject to be in the imperative mood
add a short description in the message what was broken and what was fixed

**Comment by JonasHelming** [comment]
@LukasBoll Could you update the commit message, so we can merge this?

**Comment by LukasBoll** [comment]
Thank you for the hint, I just updated the commit message.

**Review by eneufeld — APPROVED** [review]
Thank you!

**Pull request merged**
