### PR TITLE
Improve initial creation of a tutorial

### LINKED ISSUE #41: Create a new tutorial
I wanted to create a new tutorial from scratch.
So I downloaded the vsix file and installed it into VSCode.
Now I was stuck ;-) 
My questions are:
- is there a special folder (eg `.tutorial`) I need to put my new file into?
- do I need to follow name conventions (it seems like I have to, eg `foo.tut.json`)
- is there autocompletion for the json or do I need to 'know' what I have to write there?
Or is there a yeoman generator that I can use to get me kick started?

FYI, I downloaded the https://github.com/eclipsesource/theia-tutorial-extension/blob/main/schema/tutorial.json and configured my workspace to use it as the schema for all my `*.tut.json` files, but the schema seems to be outdated as this json: https://github.com/eclipsesource/glsp-tutorial/blob/main/.tutorial/glsp.tut.json shows warnings on the `typeId` property ...

Any help is appreciated ...

### PR DESCRIPTION
**Pull request by eneufeld**
- add new action to create a new tutorial
- enable autocomplete for `*.tut.json` files
- improve schema defintion
- remove old schema
- fix linting errors
- add button to exit tutorial and go back to list of tutorials

Fix #41

### CODE REVIEW

**Comment by JonasHelming** [comment]
@max-elia : Could you provide feedback please?

**Comment by max-elia** [comment]
I tested it and the changes look good to me. 
However I have a suggestion on the 'To overview' button. Since we have two different overviews (tutorials and exercises) on different levels, I added a BackArrow Button to go up one Level for both and have a consistent navigation. I opened a PR on your branch.

**Review by max-elia — APPROVED** [review]

**Comment by eneufeld** [comment]
@max-elia  Thank you. I like the improvement of the back button. I merged your change.

**Comment by JonasHelming** [comment]
@eneufeld : I am about to release a new version, can we merge this?

**Comment by eneufeld** [comment]
let me fix the new conflicts

**Comment by eneufeld** [comment]
@JonasHelming can be merged

**Pull request merged**
